### PR TITLE
Prevent multiple initialisation

### PR DESCRIPTION
**Pull request by TheMagoo73**

### CODE REVIEW

**Comment by tm1000** [comment]
This should really be merged ASAP

**Comment by TheMagoo73** [comment]
Oh heck - I totally forgot about this :(

Let me get on it...

**Comment by tm1000** [comment]
Thanks @TheMagoo73  I only noticed when I was trying to set identity in the middle of it loading global state which made it so that isLoading was always true :-|

**Comment by TheMagoo73** [comment]
Released as v1.2.3 - @tm1000 thanks for the reminder, I hope this sorts it for you.

**Pull request merged**
